FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copying over directories
COPY core/ core/
COPY network/ network/
COPY proto/ proto/
COPY scripting/ scripting/
COPY state/ state/

# Set env to ensure everything is resolved
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

# Running the Registrar entry point
CMD ["python", "-u", "-m", "network.run_registrar"]
