FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copying over directories
COPY core/ core/
COPY network/ network/
COPY proto/ proto/
COPY scripting/ scripting/
COPY state/ state/

# Expose port from network/config.py
EXPOSE 58333

ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app
