# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import energy_chain_pb2 as proto_dot_energy__chain__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/energy_chain_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodeServiceStub(object):
    """*
    --- Services ---

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitTx = channel.unary_unary(
                '/energy_chain.NodeService/SubmitTx',
                request_serializer=proto_dot_energy__chain__pb2.Transaction.SerializeToString,
                response_deserializer=proto_dot_energy__chain__pb2.SubmitResponse.FromString,
                _registered_method=True)
        self.SubmitBlock = channel.unary_unary(
                '/energy_chain.NodeService/SubmitBlock',
                request_serializer=proto_dot_energy__chain__pb2.Block.SerializeToString,
                response_deserializer=proto_dot_energy__chain__pb2.SubmitResponse.FromString,
                _registered_method=True)
        self.GetTip = channel.unary_unary(
                '/energy_chain.NodeService/GetTip',
                request_serializer=proto_dot_energy__chain__pb2.GetTipRequest.SerializeToString,
                response_deserializer=proto_dot_energy__chain__pb2.Block.FromString,
                _registered_method=True)
        self.GetBlocks = channel.unary_unary(
                '/energy_chain.NodeService/GetBlocks',
                request_serializer=proto_dot_energy__chain__pb2.GetBlocksRequest.SerializeToString,
                response_deserializer=proto_dot_energy__chain__pb2.GetBlocksResponse.FromString,
                _registered_method=True)
        self.GetPeers = channel.unary_unary(
                '/energy_chain.NodeService/GetPeers',
                request_serializer=proto_dot_energy__chain__pb2.GetPeersRequest.SerializeToString,
                response_deserializer=proto_dot_energy__chain__pb2.GetPeersResponse.FromString,
                _registered_method=True)


class NodeServiceServicer(object):
    """*
    --- Services ---

    """

    def SubmitTx(self, request, context):
        """Submit an unconfirmed Transaction to mempool 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitBlock(self, request, context):
        """Submit a new mined Block to the network 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTip(self, request, context):
        """Get the current tip of the chain 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBlocks(self, request, context):
        """Request a range of blocks 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPeers(self, request, context):
        """Node discovery 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitTx': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTx,
                    request_deserializer=proto_dot_energy__chain__pb2.Transaction.FromString,
                    response_serializer=proto_dot_energy__chain__pb2.SubmitResponse.SerializeToString,
            ),
            'SubmitBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitBlock,
                    request_deserializer=proto_dot_energy__chain__pb2.Block.FromString,
                    response_serializer=proto_dot_energy__chain__pb2.SubmitResponse.SerializeToString,
            ),
            'GetTip': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTip,
                    request_deserializer=proto_dot_energy__chain__pb2.GetTipRequest.FromString,
                    response_serializer=proto_dot_energy__chain__pb2.Block.SerializeToString,
            ),
            'GetBlocks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBlocks,
                    request_deserializer=proto_dot_energy__chain__pb2.GetBlocksRequest.FromString,
                    response_serializer=proto_dot_energy__chain__pb2.GetBlocksResponse.SerializeToString,
            ),
            'GetPeers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPeers,
                    request_deserializer=proto_dot_energy__chain__pb2.GetPeersRequest.FromString,
                    response_serializer=proto_dot_energy__chain__pb2.GetPeersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'energy_chain.NodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('energy_chain.NodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeService(object):
    """*
    --- Services ---

    """

    @staticmethod
    def SubmitTx(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/energy_chain.NodeService/SubmitTx',
            proto_dot_energy__chain__pb2.Transaction.SerializeToString,
            proto_dot_energy__chain__pb2.SubmitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/energy_chain.NodeService/SubmitBlock',
            proto_dot_energy__chain__pb2.Block.SerializeToString,
            proto_dot_energy__chain__pb2.SubmitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/energy_chain.NodeService/GetTip',
            proto_dot_energy__chain__pb2.GetTipRequest.SerializeToString,
            proto_dot_energy__chain__pb2.Block.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBlocks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/energy_chain.NodeService/GetBlocks',
            proto_dot_energy__chain__pb2.GetBlocksRequest.SerializeToString,
            proto_dot_energy__chain__pb2.GetBlocksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPeers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/energy_chain.NodeService/GetPeers',
            proto_dot_energy__chain__pb2.GetPeersRequest.SerializeToString,
            proto_dot_energy__chain__pb2.GetPeersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
